import React from 'react';

// ============================================================================
// COMMUNITY STYLES
// Shared styles for community components
// ============================================================================

export const communityStyles: { [key: string]: React.CSSProperties } = {
  pageContainer: {
    display: 'flex',
    height: 'calc(100vh - 100px)',
    background: 'linear-gradient(180deg, #0D0811 0%, #1A0F1E 100%)',
  },
  leftSidebar: {
    width: '260px',
    background: 'linear-gradient(180deg, rgba(45, 31, 61, 0.4) 0%, rgba(26, 15, 30, 0.6) 100%)',
    borderRight: '1px solid rgba(74, 44, 90, 0.4)',
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
  },
  sidebarHeader: {
    padding: '16px',
    borderBottom: '1px solid rgba(74, 44, 90, 0.4)',
    color: '#D4A84B',
    fontWeight: 600,
    fontSize: '1.05rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1rem',
    padding: '4px 8px',
    borderRadius: '6px',
    color: '#B8B4C8',
    transition: 'all 0.2s',
  },
  emptyState: { padding: '20px', textAlign: 'center', color: '#B8B4C8' },
  category: { marginBottom: '5px' },
  categoryHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 15px',
    color: '#B8B4C8',
    fontSize: '0.8rem',
    cursor: 'pointer',
    textTransform: 'uppercase',
    letterSpacing: '0.03em',
  },
  categoryName: { fontWeight: 600 },
  channel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 15px 10px 25px',
    color: '#B8B4C8',
    cursor: 'pointer',
    borderRadius: '8px',
    margin: '2px 8px',
    transition: 'all 0.2s',
  },
  channelActive: {
    background: 'rgba(212, 168, 75, 0.15)',
    color: '#F0EDF4',
    borderLeft: '2px solid #D4A84B',
  },
  channelHash: { color: '#7B5EA7' },
  channelBadge: { marginLeft: 'auto', fontSize: '0.8rem' },
  onlineSection: {
    marginTop: 'auto',
    borderTop: '1px solid rgba(74, 44, 90, 0.4)',
    padding: '12px',
  },
  onlineHeader: {
    padding: '8px',
    color: '#B8B4C8',
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.03em',
  },
  onlineUser: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 8px',
    fontSize: '0.9rem',
  },
  onlineIndicator: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#4ade80',
    boxShadow: '0 0 6px rgba(74, 222, 128, 0.5)',
  },
  onlineUsername: { color: '#F0EDF4' },
  mainContent: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  secondaryNav: {
    display: 'flex',
    gap: '8px',
    padding: '12px 20px',
    borderBottom: '1px solid rgba(74, 44, 90, 0.4)',
    background: 'rgba(45, 31, 61, 0.3)',
  },
  secondaryTab: {
    padding: '10px 20px',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#B8B4C8',
    fontSize: '0.95rem',
    cursor: 'pointer',
    borderRadius: '8px',
    transition: 'all 0.2s',
    fontWeight: 500,
  },
  secondaryTabActive: { background: 'rgba(212, 168, 75, 0.2)', color: '#D4A84B' },
  chatContainer: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  chatHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid rgba(74, 44, 90, 0.4)',
    background: 'rgba(45, 31, 61, 0.3)',
  },
  chatChannelName: { color: '#F0EDF4', fontWeight: 600, fontSize: '1.1rem' },
  chatChannelDesc: { color: '#B8B4C8', fontSize: '0.9rem', marginLeft: '15px' },
  messagesContainer: { flex: 1, overflowY: 'auto', padding: '20px' },
  noMessages: { textAlign: 'center', color: '#B8B4C8', padding: '40px' },
  message: { marginBottom: '20px' },
  messageHeader: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' },
  messageBadge: { fontSize: '1.1rem' },
  messageUsername: { color: '#D4A84B', fontWeight: 600 },
  messageTime: { color: '#7A7490', fontSize: '0.8rem' },
  messageContent: { color: '#F0EDF4', paddingLeft: '28px' },
  inputContainer: {
    display: 'flex',
    gap: '10px',
    padding: '16px 20px',
    borderTop: '1px solid rgba(74, 44, 90, 0.4)',
    background: 'rgba(45, 31, 61, 0.3)',
  },
  messageInput: {
    flex: 1,
    padding: '12px 16px',
    backgroundColor: 'rgba(13, 8, 17, 0.8)',
    border: '1px solid rgba(74, 44, 90, 0.5)',
    borderRadius: '10px',
    color: '#F0EDF4',
    fontSize: '1rem',
    transition: 'border-color 0.2s',
  },
  sendBtn: {
    padding: '12px 24px',
    background: 'linear-gradient(135deg, #D4A84B 0%, #B8923A 100%)',
    border: 'none',
    borderRadius: '10px',
    color: '#1A0F1E',
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(212, 168, 75, 0.3)',
  },
  leaderboardContainer: { padding: '20px', overflowY: 'auto' },
  leaderboardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    color: '#D4A84B',
  },
  leaderboardSelect: {
    padding: '10px 16px',
    backgroundColor: 'rgba(13, 8, 17, 0.8)',
    border: '1px solid rgba(74, 44, 90, 0.5)',
    borderRadius: '8px',
    color: '#F0EDF4',
  },
  leaderboardList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  leaderboardEntry: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '18px 22px',
    background: 'linear-gradient(180deg, rgba(45, 31, 61, 0.5) 0%, rgba(26, 15, 30, 0.7) 100%)',
    borderRadius: '14px',
    border: '1px solid rgba(74, 44, 90, 0.4)',
    flexWrap: 'wrap',
    transition: 'all 0.2s',
  },
  leaderboardRankBadge: { minWidth: '45px', textAlign: 'center' },
  rankNumber: { fontWeight: 700, fontSize: '1.1rem' },
  badgeStack: { display: 'flex', alignItems: 'center', gap: '4px', fontSize: '1.2rem', minWidth: '80px' },
  roleBadge: { fontSize: '1.3rem' },
  moreBadges: {
    fontSize: '0.7rem',
    color: '#B8B4C8',
    backgroundColor: 'rgba(74, 44, 90, 0.5)',
    padding: '2px 6px',
    borderRadius: '10px',
  },
  userInfo: { display: 'flex', flexDirection: 'column', gap: '2px', minWidth: '120px', flex: '1' },
  leaderboardName: { fontWeight: 600, fontSize: '1rem' },
  roleTag: { fontSize: '0.7rem', color: '#7B5EA7', textTransform: 'uppercase', letterSpacing: '0.5px' },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '12px', marginLeft: 'auto' },
  statItem: { display: 'flex', flexDirection: 'column', alignItems: 'center', minWidth: '60px' },
  statLabel: { fontSize: '0.65rem', color: '#B8B4C8', textTransform: 'uppercase', letterSpacing: '0.5px' },
  statValue: { fontSize: '0.9rem', fontWeight: 600, color: '#F0EDF4' },
  leaderboardValue: { color: '#D4A84B', fontWeight: 600 },
  forumsContainer: { padding: '20px' },
  loading: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 'calc(100vh - 100px)',
    color: '#D4A84B',
    fontSize: '1.2rem',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(13, 8, 17, 0.92)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modal: {
    background: 'linear-gradient(180deg, #2D1F3D 0%, #1A0F1E 100%)',
    padding: '28px',
    borderRadius: '16px',
    border: '1px solid rgba(212, 168, 75, 0.3)',
    width: '100%',
    maxWidth: '450px',
    boxShadow: '0 24px 48px rgba(0, 0, 0, 0.5)',
  },
  modalTitle: { color: '#D4A84B', margin: '0 0 20px', fontWeight: 600 },
  formGroup: { marginBottom: '16px' },
  label: { display: 'block', color: '#B8B4C8', marginBottom: '6px', fontSize: '0.9rem', fontWeight: 500 },
  input: {
    width: '100%',
    padding: '12px 14px',
    backgroundColor: 'rgba(13, 8, 17, 0.8)',
    border: '1px solid rgba(74, 44, 90, 0.5)',
    borderRadius: '10px',
    color: '#F0EDF4',
    fontSize: '1rem',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s',
  },
  select: {
    width: '100%',
    padding: '12px 14px',
    backgroundColor: 'rgba(13, 8, 17, 0.8)',
    border: '1px solid rgba(74, 44, 90, 0.5)',
    borderRadius: '10px',
    color: '#F0EDF4',
    fontSize: '1rem',
  },
  modalActions: { display: 'flex', gap: '12px', marginTop: '24px' },
  cancelBtn: {
    flex: 1,
    padding: '12px',
    backgroundColor: 'transparent',
    border: '1px solid rgba(74, 44, 90, 0.5)',
    borderRadius: '10px',
    color: '#B8B4C8',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  submitBtn: {
    flex: 1,
    padding: '12px',
    background: 'linear-gradient(135deg, #D4A84B 0%, #B8923A 100%)',
    border: 'none',
    borderRadius: '10px',
    color: '#1A0F1E',
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(212, 168, 75, 0.3)',
  },
  messageActions: { marginLeft: 'auto', display: 'flex', gap: '4px', opacity: 0.6 },
  actionBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.9rem',
    padding: '2px 6px',
    borderRadius: '4px',
    transition: 'all 0.2s',
  },
  replyIndicator: {
    paddingLeft: '28px',
    marginBottom: '4px',
    fontSize: '0.85rem',
    borderLeft: '2px solid rgba(74, 44, 90, 0.5)',
    paddingTop: '2px',
    paddingBottom: '2px',
  },
  replyBanner: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 20px',
    background: 'rgba(212, 168, 75, 0.1)',
    borderTop: '1px solid rgba(212, 168, 75, 0.3)',
    color: '#F0EDF4',
    fontSize: '0.9rem',
  },
  cancelReplyBtn: {
    background: 'none',
    border: 'none',
    color: '#B8B4C8',
    cursor: 'pointer',
    fontSize: '1rem',
    padding: '4px 8px',
  },
  editForm: { display: 'flex', gap: '8px', paddingLeft: '28px', alignItems: 'center' },
  editInput: {
    flex: 1,
    padding: '10px 14px',
    backgroundColor: 'rgba(13, 8, 17, 0.8)',
    border: '1px solid rgba(212, 168, 75, 0.4)',
    borderRadius: '8px',
    color: '#F0EDF4',
    fontSize: '0.95rem',
  },
  editSaveBtn: {
    padding: '10px 18px',
    background: 'linear-gradient(135deg, #4ADE80 0%, #22C55E 100%)',
    border: 'none',
    borderRadius: '8px',
    color: '#1A0F1E',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  editCancelBtn: {
    padding: '10px 18px',
    backgroundColor: 'transparent',
    border: '1px solid rgba(74, 44, 90, 0.5)',
    borderRadius: '8px',
    color: '#B8B4C8',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  paginationContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    background: 'rgba(45, 31, 61, 0.3)',
    borderTop: '1px solid rgba(74, 44, 90, 0.4)',
    marginTop: '10px',
    borderRadius: '0 0 14px 14px',
    flexWrap: 'wrap' as const,
    gap: '10px',
  },
  paginationInfo: { display: 'flex', alignItems: 'center', gap: '15px' },
  paginationText: { color: '#B8B4C8', fontSize: '0.9rem' },
  paginationControls: { display: 'flex', alignItems: 'center', gap: '8px' },
  pageSizeSelect: {
    padding: '8px 12px',
    backgroundColor: 'rgba(13, 8, 17, 0.8)',
    border: '1px solid rgba(74, 44, 90, 0.5)',
    borderRadius: '8px',
    color: '#F0EDF4',
    fontSize: '0.85rem',
    cursor: 'pointer',
  },
  pageButton: {
    padding: '8px 14px',
    background: 'rgba(74, 44, 90, 0.4)',
    border: 'none',
    borderRadius: '8px',
    color: '#F0EDF4',
    cursor: 'pointer',
    fontSize: '0.85rem',
    transition: 'all 0.2s',
  },
  pageIndicator: { padding: '8px 14px', color: '#D4A84B', fontSize: '0.9rem', fontWeight: 600 },
  findMeButton: {
    padding: '10px 18px',
    background: 'linear-gradient(135deg, #D4A84B 0%, #B8923A 100%)',
    border: 'none',
    borderRadius: '8px',
    color: '#1A0F1E',
    cursor: 'pointer',
    fontSize: '0.85rem',
    fontWeight: 600,
    transition: 'all 0.2s',
    boxShadow: '0 2px 8px rgba(212, 168, 75, 0.3)',
  },
};
